addons: 
  apt:
    packages:
      - graphviz
before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj/app"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install:
  - "chmod +x ./travis.sh"
install: java --version 
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/maven
jdk: openjdk14
dist: xenial
env: 
  - TARGET=BUILD
branches:
  only:
    - master
    - dev
language: java
notifications: 
  email: false
sudo: false
script: "./travis.sh"
