addons: 
  apt:
    packages:
      - graphviz
before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj/app"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install: 
  - "chmod +x ./travis.sh"
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/jvm
    - $HOME/maven
env: 
  - TARGET=BUILD JDK='OpenJDK 9'
install: . ./install-jdk.sh -F 9 -L GPL
branches:
  only:
    - master
    - dev
language: java
notifications: 
  email: false
script: "./travis.sh"
sudo: false
