version: '3.6'
services:
  db:
    container_name: ligoj-db
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: ligoj
      MYSQL_USER: ligoj
      MYSQL_PASSWORD: ligoj
    volumes:
      - ${LIGOJ_DATA:-/var/ligoj/mysql}:/var/lib/mysql
    networks:
      - ligoj-network
  api:
    container_name: ligoj-api
    image: ligoj/ligoj-api:3.0.0
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8081"
      CUSTOM_OPTS: "-Djdbc.host=ligoj-db"
      CRYPTO: "-Dapp.crypto.password=public"
    links:
      - db:ligoj-db
    depends_on: 
      - db
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
  ui:
    container_name: ligoj-ui
    image: ligoj/ligoj-ui:3.0.0
    environment:
      JAVA_OPTIONS: "-Dsecurity=Rest"
      SERVER_PORT: "8080"
      CUSTOM_OPTS: ""
    links:
      - api:ligoj-api
    ports: 
      - "8080:8080"
    networks:
      - ligoj-network
 networks:
   ligoj-network:
